services:
  db:
    image: postgres:15
    container_name: cafe-postgres
    environment:
      POSTGRES_USER: cafe
      POSTGRES_PASSWORD: cafe
      POSTGRES_DB: cafe_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cafe -d cafe_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: cafe-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: cafe-app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://cafe:cafe@db:5432/cafe_db
      REDIS_URL: redis://redis:6379
      SECRET_KEY: change-me-in-prod
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      HOST: 0.0.0.0
      PORT: 8000
      DEBUG: "True"
    ports:
      - "8000:8000"
    # Uncomment to mount local code for live reload in dev (requires extra deps)
    # volumes:
    #   - .:/app

volumes:
  db_data:


